name: Test Industrial CI pipeline
on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: melodic
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
